name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest


    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias para tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest redis flask

      - name: Ejecutar tests unitarios vote
        env:
          REDIS_HOST: localhost
        run: |
          cd vote
          pytest test_app.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar tests unitarios result
        run: |
          cd result
          npm install
          npm test


      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build servicio Vote
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote-app:latest ./vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote-app:latest

      - name: Build servicio Result
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result-app:latest ./result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result-app:latest

      - name: Build servicio Worker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:latest ./worker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:latest
