name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build servicio Vote
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote-app:latest ./vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote-app:latest

      - name: Build servicio Result
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result-app:latest ./result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result-app:latest

      - name: Build servicio Worker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:latest ./worker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker-app:latest
